Types
azerothcore/wow-statistics pull request #18
Opened 2021-03-05 20:54 UTC by Repcan

Added:
.tsx typescript
prettier settings
footer

2021-03-05 22:31 UTC, Helias commented
Thank you a lot!
This is really good :wink:

2021-03-05 22:36 UTC, Helias approved these changes

2021-03-06 15:48 UTC, Hacaw requested changes
Thanks for the contribution @Repcan !
You actually manage to fix 2 issues, so I linked them to this pull-request.
I also left some comments more or less mandatory, please check them and after that we can merge this 💯

2021-03-06 15:48 UTC, Hacaw commented on src/components/Footer.css
> +footer {
Since we are component driven try to put the everything related to Footer in a Footer folder under /components

2021-03-06 15:48 UTC, Hacaw commented on src/components/Footer.tsx
> +          <strong>ShinDarth</strong>
Hacaw and Helias

2021-03-06 15:48 UTC, Hacaw commented on src/components/Footer.tsx
> +          href="https://github.com/FrancescoBorzi/PvPstats/blob/master/LICENSE"
We have our own license to point to: https://github.com/azerothcore/wow-statistics/blob/master/LICENSE

2021-03-06 15:48 UTC, Hacaw commented on src/components/shared/Chart.css
> +@media (min-width: 768px) {
I am no .css guy, but what does this improvement add ? 

Having the window at > 768 pixels the chart still looks bad with this fix or not. 
Maybe there is an example I am missing.

2021-03-06 15:48 UTC, Hacaw commented on .prettierrc
> +  "jsxSingleQuote": true
Nice, interesting !

2021-03-06 15:48 UTC, Hacaw commented on .env.example
> +REACT_APP_SERVER_TITLE=Wow
Cool, even though we git ignore files, it's useful to have .example file.

2021-03-06 15:48 UTC, Hacaw commented on src/react-app-env.d.ts
> +/// <reference types="react-scripts" />
Is this related to the .env.example file you created to make it work?

2021-03-06 22:33 UTC, Helias commented on src/components/Footer.tsx
> +          <strong>ShinDarth</strong>
lol

2021-03-08 17:05 UTC, Hacaw approved these changes

2021-03-08 18:33 UTC, Helias approved these changes

2021-03-08 20:00 UTC, merged